name: A day in a pile of work
url: https://arteymix.github.io
author: Guillaume Poirier-Morency <guillaumepoiriermorency@gmail.com>
description: My personal web development blog

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'Makefile']

paginate: 10

markdown:    redcarpet
highlighter: pygments

gems:
  - jekyll-sitemap
