name: A Day in a Pile of Work
url: https://arteymix.github.io
author: Guillaume Poirier-Morency <guillaumepoiriermorency@gmail.com>
description: My personal Web development blog

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'Makefile']

paginate: 10

gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-mentions
